Repository playframework/play1, pull requests merged in 2019-04, with the labels that each got.

#1299 #1298: Handle only private key info from PEM
  framework/dependencies.yml
  framework/lib/bcpkix-jdk15on-1.60.jar
  framework/lib/bcpkix-jdk15on-1.61.jar
  framework/lib/bcprov-jdk15on-1.60.jar
  framework/src/play/server/ssl/SslHttpServerContextFactory.java
Labels: improvement

#1222 [#2155] Silent or suppressed errors in unittest PluginCollectionTest#skipsDuplicatePlugins
  framework/test-src/play/plugins/PluginCollectionTest.java
  framework/test-src/play/plugins/custom-play.duplicate.plugins
  framework/test-src/play/plugins/custom-play.plugins.duplicate
Labels: defect

#1156 [#2128] feature: help for module commands
  framework/pym/play/commands/help.py
  play
Labels: improvement

#1305 documentation(1.5.3): add Play 1.5.3 documentation
  documentation/manual/releases/release1.4.x/releasenotes-1.4.6.textile
  documentation/manual/releases/release1.5.x/releasenotes-1.5.3.textile
  documentation/manual/releases/releases.textile
Labels: documentation
