Repository playframework/play1, pull requests merged in 2022-06, with the labels that each got.

#1411 Do not overwrite system property net.spy.log.LoggerImpl -> 1.7.1
  framework/src/play/cache/MemcachedImpl.java
Labels: defect

#1409 update check of java version
  framework/pym/play/application.py
Labels: improvement

#1416 Prepare release 1.7.1
  documentation/manual/home.textile
  documentation/manual/releases/release1.7.x/releasenotes-1.7.1.textile
  documentation/manual/releases/releases.textile
Labels: documentation
