Repository playframework/play1, pull requests merged in 2022-04, with the labels that each got.

#1393 [#1383] ♻ Support disabled evolutions for command line operations
  framework/src/play/db/Evolutions.java
Labels: feature, improvement

#1344 MultiDb: Additional documentation
  documentation/manual/configuration.textile
Labels: documentation

#1395 [#1278, #1343] OrderBy support in simplified JPA queries for 1.5.x
  documentation/manual/jpa.textile
  framework/src/play/db/jpa/JPQL.java
  framework/test-src/play/db/jpa/JPQLTest.java
Labels: defect

#1396 [1.7.0] add releasenotes-1.7.0.textile
  documentation/manual/home.textile
  documentation/manual/releases/release1.7.x/releasenotes-1.7.0.textile
  documentation/manual/releases/releases.textile
Labels: documentation

#1400 fixed #1399 "UnboundLocalError: local variable 'playHome' referenced before assignment
  framework/pym/play/commands/intellij.py
Labels: defect
