Repository playframework/play1, pull requests merged in 2024-03, with the labels that each got.

#1469 feat(YamlParser): add SafeConstructor to enforce security
  framework/src/play/deps/YamlParser.java
Labels: defect, security

#1467 #1466 The clock function was removed from time module in Python 3.8
  framework/pym/play/commands/modulesrepo.py
Labels: has-pr, improvement

#1470 documentation(release): update documentation for release 1.8.0
  documentation/manual/home.textile
  documentation/manual/releases/release1.8.x/releasenotes-1.8.0.textile
  documentation/manual/releases/releases.textile
Labels: documentation

#1472 Fix "play build-module" by replacing yaml.load with yaml.safe_load
  framework/pym/play/commands/modulesrepo.py
Labels: defect

#1474 Convert README from textile to markdown
  README.md
  README.textile
Labels: improvement

#1473 feat(dependabot): add dependabot.yml configuration
  .github/dependabot.yml
  .github/release-drafts/increasing-minor-version.yml
  .github/release-drafts/release-drafter.yml
  .github/workflows/codeql.yml
Labels: improvement

#1477 GitHub actions configuration
  .github/workflows/build-test.yml
  .github/workflows/delete-caches.yml
  .github/workflows/release-drafter.yml
Labels: improvement

#1478 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/release-drafts/increasing-minor-version.yml
Labels: improvement

#1479 fix(release-draft): fix version number
  .github/release-drafts/increasing-minor-version.yml
Labels: improvement
